
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Analytics'
version: '1.6.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  Analytics:
    internal:
      +database: dbt_internal
    reporting:
      +database: data_reports
      +materialized: table
    warehouse:
      +database: data_warehouse
      +materialized: table

snapshots:
  Analytics:
    +target_schema: snapshots
    +strategy: check
    +check_cols: all
    +invalidate_hard_deletes: true

    google_sheets:
      snp_google_sheets__linear_regression_v1:
        +unique_key: x

    snowflake:
      +check_cols: ['dv_hashdiff']
      snp_snowflake__metering_history_v1:
        +unique_key: metering_history_id
      snp_snowflake__query_history_v1:
        +unique_key: query_id
      snp_snowflake__stage_storage_usage_history_v1:
        +unique_key: usage_date
      snp_snowflake__warehouse_metering_history_v1:
        +unique_key: warehouse_metering_history_id

    snowflake_usage:
      +invalidate_hard_deletes: false
      snp_snowflake_usage__service_v1:
        +unique_key: service_usage_id
      snp_snowflake_usage__query_v1:
        +unique_key: query_id
      snp_snowflake_usage__storage_v1:
        +unique_key: usage_date
      snp_snowflake_usage__warehouse_v1:
        +unique_key: warehouse_usage_id

    tasty_bytes:
      snp_tasty_bytes__city_v1:
        +unique_key: city_id
      snp_tasty_bytes__customer_v1:
        +unique_key: customer_id
      snp_tasty_bytes__franchise_v1:
        +unique_key: franchise_city_id
      snp_tasty_bytes__location_v1:
        +unique_key: location_id
      snp_tasty_bytes__menu_v1:
        +unique_key: menu_item_id
      snp_tasty_bytes__order_detail_v1:
        +unique_key: order_detail_id
      snp_tasty_bytes__order_header_v1:
        +unique_key: order_id
      snp_tasty_bytes__truck_v1:
        +unique_key: truck_id
