
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Analytics'
version: '1.6.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  Analytics:
    internal:
      +database: dbt_internal
    warehouse:
      +database: data_warehouse
      +materialized: table
    data_reports:
      +database: data_reports
      +materialized: table

snapshots:
  Analytics:
    +target_database: dbt_internal
    +target_schema: snapshots
    +strategy: check
    +check_cols: all

    tasty_bytes:
      scd_tasty_bytes__city:
        +unique_key: city_id
      scd_tasty_bytes__customer:
        +unique_key: customer_id
      scd_tasty_bytes__franchise:
        +unique_key: franchise_id
      scd_tasty_bytes__franchise_city:
        +unique_key: franchise_city_id
      scd_tasty_bytes__location:
        +unique_key: location_id
      scd_tasty_bytes__menu:
        +unique_key: menu_id
      scd_tasty_bytes__order_detail:
        +unique_key: order_detail_id
      scd_tasty_bytes__order_header:
        +unique_key: order_id
      scd_tasty_bytes__truck:
        +unique_key: truck_id
